# Results {#sec-analysis}

```{r dependencies}
library(dplyr)
library(ggplot2)
```

```{r}
knitr::opts_chunk$set(cache=TRUE)
```


```{r ggplot2_theme}
owntheme <- theme(legend.position = "bottom",
                  title=element_text(face="bold", size=24),
                  axis.title = element_text(face="bold", size=20),
                  legend.text = element_text(face="plain", size=20),
                  legend.title = element_blank(), 
                  axis.text = element_text(size=16)) 
```


## Simulation study 1: LFC setting

### Main results
```{r load_data_lfc}
## process path if needed (corresponding to out.dir in "R/cases_simstudy_lfc.R")
data_lfc <- readr::read_csv2("E:/cases_SIM/cases_SIM_results/cases_SIM_LFC.csv")

data_lfc <- data_lfc %>%
  mutate(Adjustment = recode_factor(interaction(adjustment, pars),
                                    "none.list()" = "none",
                                    "bonferroni.list()"="Bonferroni", 
                                    "maxt.list()" = "maxT",
                                    "mbeta.list()" = "mBeta",
                                    "bootstrap.list(type='wild')" = "Bootstrap (wild)",
                                    "bootstrap.list()" = "Bootstrap (pairs)"))

dim(data_lfc)
```

```{r}
data_lfc <- data_lfc %>% 
  filter(cortype == "equi") %>% 
  filter(rhose == 0.5) %>%
  filter(transformation == "none") 

dim(data_lfc)
```



```{r results_lfc_fwer_main}
data_lfc %>% 
  filter(n<1000, prev==0.25, se==0.8, m==10) %>%
  group_by(Adjustment, n, prev, se, m) %>%
  summarize(nsim=n(), rr = mean(fp > 0)) %>%
  ggplot(aes(n, rr, col=Adjustment, fill=Adjustment, pch=Adjustment))+
  geom_point(size=6, alpha=0.6) +
  geom_line(size=2, alpha=0.6) +
  xlab("Total sample size") +
  ylab("FWER") +
  scale_shape_manual(values = c(21, 22, 24, 25, 23, 23)) +
  geom_hline(yintercept=0.025, col="red", lwd=2, lty=2, alpha=0.75) +
  owntheme
```


```{r results_lfc_power_main}
data_lfc %>% 
  filter(n<1000, prev==0.25, se==0.8, m==10) %>%
  group_by(Adjustment, n, prev, se, m) %>%
  summarize(nsim=n(), rr = mean(`0.05` > 0)) %>%
  ggplot(aes(n, rr, col=Adjustment, fill=Adjustment, pch=Adjustment)) +
  geom_point(size=6, alpha=0.6) +
  geom_line(size=2, alpha=0.6) +
  xlab("Total sample size") +
  ylab("Power") + 
  scale_shape_manual(values = c(21, 22, 24, 25, 23, 23)) +
  owntheme
```


### Sensitivity analyses

```{r results_lfc_fwer_sens, out.width="100%", fig.asp = 2}
data_lfc %>% 
  filter(n<1000) %>%
  group_by(Adjustment, n, prev, se, m) %>%
  summarize(nsim=n(), rr = mean(fp > 0)) %>%
  ggplot(aes(n, rr, col=Adjustment, fill=Adjustment, pch=Adjustment))+
  geom_point(size=6, alpha=0.6) +
  geom_line(size=2, alpha=0.6) +
  xlab("Total sample size") +
  ylab("FWER") +
  scale_shape_manual(values = c(21, 22, 24, 25, 23, 23)) +
  geom_hline(yintercept=0.025, col="red", lwd=2, lty=2, alpha=0.75) +
  owntheme +
  facet_wrap(prev+se ~ m, ncol=2, 
             labeller = label_bquote("prev = " ~ .(prev) * ", " * "se = " ~ .(se) * ", " * "m = " ~ .(m)))
```


```{r lfc_power_sens_a, out.width="100%", fig.asp = 2}
data_lfc %>% 
  filter(n<1000) %>%
  group_by(Adjustment, n, prev, se, m) %>%
  summarize(nsim=n(), rr = mean(`0.05` > 0)) %>%
  ggplot(aes(n, rr, col=Adjustment, fill=Adjustment, pch=Adjustment)) +
  geom_point(size=6, alpha=0.6) +
  geom_line(size=2, alpha=0.6) +
  xlab("Total sample size") +
  ylab("Power") + 
  scale_shape_manual(values = c(21, 22, 24, 25, 23, 23)) +
  owntheme +
  facet_wrap(prev+se ~ m, ncol=2, 
             labeller = label_bquote("prev = " ~ .(prev) * ", " * "se = " ~ .(se) * ", " * "m = " ~ .(m)))
```



```{r lfc_power_sens_b, out.width="100%", fig.asp = 2}
data_lfc %>% 
  filter(n<1000) %>%
  group_by(Adjustment, n, prev, se, m) %>%
  summarize(nsim=n(), rr = mean(`0.1` > 0)) %>%
  ggplot(aes(n, rr, col=Adjustment, fill=Adjustment, pch=Adjustment)) +
  geom_point(size=6, alpha=0.6) +
  geom_line(size=2, alpha=0.6) +
  xlab("Total sample size") +
  ylab("Power") + 
  scale_shape_manual(values = c(21, 22, 24, 25, 23, 23)) +
  owntheme +
  facet_wrap(prev+se ~ m, ncol=2, 
             labeller = label_bquote("prev = " ~ .(prev) * ", " * "se = " ~ .(se) * ", " * "m = " ~ .(m)))
```



## Simulation study 2: ROC setting


### Main results

```{r data_load_roc, cache=FALSE}
## process path if needed (corresponding to out.dir in "R/cases_simstudy_roc.R")
data_roc <- readr::read_csv2("E:/cases_SIM/cases_SIM_results/cases_SIM_ROC.csv")

data_roc <- data_roc %>%
  mutate(Adjustment = recode_factor(interaction(adjustment, pars),
                                    "none.list()" = "none",
                                    "bonferroni.list()"="Bonferroni", 
                                    "maxt.list()" = "maxT",
                                    "mbeta.list()" = "mBeta",
                                    "bootstrap.list(type='wild')" = "Bootstrap (wild)",
                                    "bootstrap.list()" = "Bootstrap (pairs)"))


dim(data_roc)

```



```{r data_preproc_roc}
data_roc <- data_roc %>% 
  filter(rhose == 0.5) %>%
  filter(auc == "seq(0.85, 0.90, length.out = 5)") %>% 
  filter(transformation == "none") 

dim(data_roc)
```



```{r results_roc_fwer_main}
data_roc %>% 
  filter(n<1000, prev==0.25, m==10) %>%
  group_by(Adjustment, n, prev, m) %>%
  summarize(nsim=n(), rr = mean(`0` > 0)) %>%
  ggplot(aes(n, rr, col=Adjustment, fill=Adjustment, pch=Adjustment))+
  geom_point(size=6, alpha=0.6) +
  geom_line(size=2, alpha=0.6) +
  xlab("Total sample size") +
  ylab("FWER") +
  scale_shape_manual(values = c(21, 22, 24, 25, 23, 23)) +
  geom_hline(yintercept=0.025, col="red", lwd=2, lty=2, alpha=0.75) +
  owntheme 
```


```{r results_roc_power_main}
data_roc %>% 
  filter(n<1000, prev==0.25, m==10) %>%
  group_by(Adjustment, n, prev, m) %>%
  summarize(nsim=n(), rr = mean(`0.1` > 0)) %>%
  ggplot(aes(n, rr, col=Adjustment, fill=Adjustment, pch=Adjustment)) +
  geom_point(size=6, alpha=0.6) +
  geom_line(size=2, alpha=0.6) +
  xlab("Total sample size") +
  ylab("Power") + 
  scale_shape_manual(values = c(21, 22, 24, 25, 23, 23)) +
  owntheme 
```


### Sensitivity analyses

```{r results_roc_fwer_sens, out.width="100%", fig.asp = 1}
data_roc %>% 
  filter(n<1000) %>%
  group_by(Adjustment, n, prev, m) %>%
  summarize(nsim=n(), rr = mean(`0` > 0)) %>%
  ggplot(aes(n, rr, col=Adjustment, fill=Adjustment, pch=Adjustment))+
  geom_point(size=6, alpha=0.6) +
  geom_line(size=2, alpha=0.6) +
  xlab("Total sample size") +
  ylab("FWER") +
  scale_shape_manual(values = c(21, 22, 24, 25, 23, 23)) +
  geom_hline(yintercept=0.025, col="red", lwd=2, lty=2, alpha=0.75) +
  owntheme +
  facet_wrap(prev ~ m, ncol=2, 
             labeller = label_bquote("prev = " ~ .(prev) * ", " * "m = " ~ .(m)))
```


```{r results_roc_power_sens_a, out.width="100%", fig.asp = 1}
data_roc %>% 
  filter(n<1000) %>%
  group_by(Adjustment, n, prev, m) %>%
  summarize(nsim=n(), rr = mean(`0.1` > 0)) %>%
  ggplot(aes(n, rr, col=Adjustment, fill=Adjustment, pch=Adjustment)) +
  geom_point(size=6, alpha=0.6) +
  geom_line(size=2, alpha=0.6) +
  xlab("Total sample size") +
  ylab("Power") + 
  scale_shape_manual(values = c(21, 22, 24, 25, 23, 23)) +
  owntheme +
  facet_wrap(prev ~ m, ncol=2, 
             labeller = label_bquote("prev = " ~ .(prev) * ", " * "m = " ~ .(m)))
```


```{r results_roc_power_sens_b, out.width="100%", fig.asp = 1}
data_roc %>% 
  filter(n<1000) %>%
  group_by(Adjustment, n, prev, m) %>%
  summarize(nsim=n(), rr = mean(`0.05` > 0)) %>%
  ggplot(aes(n, rr, col=Adjustment, fill=Adjustment, pch=Adjustment)) +
  geom_point(size=6, alpha=0.6) +
  geom_line(size=2, alpha=0.6) +
  xlab("Total sample size") +
  ylab("Power") + 
  scale_shape_manual(values = c(21, 22, 24, 25, 23, 23)) +
  owntheme +
  facet_wrap(prev ~ m, ncol=2, 
             labeller = label_bquote("prev = " ~ .(prev) * ", " * "m = " ~ .(m)))
```