# Overview {.unnumbered}

[Westphal \& Zapf, 2024](https://journals.sagepub.com/doi/epub/10.1177/09622802241236933) investigated different multiple comparison procedures (MCPs) for a certain type of analyis (e.g.) relevant in diagnostic accuracy studies, the so-called co-primary endpoint analysis.

The R package [cases](https://github.com/maxwestphal/cases/) contains user-friendly implementations of these MCPs.

This R project **cases_simstudy** contains a reproducible description of the implementation and results of this simulation study in form of a [quarto book](https://quarto.org/docs/books). The GitHub repository for this project is [github.com/maxwestphal/cases_simstudy](https://github.com/maxwestphal/cases_simstudy)

**This report is not meant to a standalone resource but rather should be read in addition to the main paper.**

In addition, the R script **cases_simstudy_paper_figures.R** allows to reproduce
the figures in the main paper.

## References

1. Westphal M, Zapf A. Statistical inference for diagnostic test accuracy studies with multiple comparisons. Statistical Methods in Medical Research. 2024;0(0). [doi:10.1177/09622802241236933](https://journals.sagepub.com/doi/full/10.1177/09622802241236933)

